# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('DONE', 'DONE')], default='TODO', max_length=4),
        ),
    ]
